### ISSUE TITLE
Example for using SPS

### ISSUE THREAD

**Issue by thhung** [IssamLaradji/sps#1]
Hi, 

  Thanks for sharing your code. Could you provide a simple example for using your SPS (transfer learning for example)? As far as I understand, we could not use it as simple as replacement for Adam for example since we need some preprocessing. Please correct me if I'm wrong.

**Comment by IssamLaradji** [comment]
Thanks for your interest! I added a `Usage` section in the README.md https://github.com/IssamLaradji/sps#2-usage

A full example is shown here as well: https://github.com/IssamLaradji/sps/blob/master/tests/test_basic.py

Please let me know if it doesn't work.

**Comment by thhung** [comment]
Thanks, Issam. It was much simpler than I thought.
