### ISSUE TITLE
Query: Differnce vs Adadelta?

### ISSUE THREAD

**Issue by abduallahmohamed** [IssamLaradji/sps#3]
Hi, 
Thanks for your work. I was wondering about the difference between your method and Adadelta?

**Comment by IssamLaradji** [comment]
You welcome! 

The difference is that `Adadelta` belongs to the `Adagrad` family and as such accumulates past gradients to get the step size, while `SPS` only uses the gradient norm of only the current iteration. Further, it looks like that `AdaDelta` has slow convergence [1]  whereas `SPS` has a fast convergence rate when interpolation is satisfied.

[1] http://akyrillidis.github.io/notes/AdaDelta
